### ISSUE TITLE
Hi, I try to follow the default step to install AWX on K3S. However, cannot access proxy no IP assigned...

### ISSUE THREAD

**Issue by noname1314** [kurokobo/awx-on-k3s#158]
As titled.

![image](https://user-images.githubusercontent.com/22712192/205615065-96d90fec-05b9-4154-9b98-36c367cf9dcb.png)

**Comment by noname1314** [comment]
Normal behavior

![image](https://user-images.githubusercontent.com/22712192/205615308-a0130214-80cd-4fd3-b081-6056ef764337.png)

**Comment by kurokobo** [comment]
I can't understand your situation in detail. Please describe your environment and provide steps to reproduce.

**Comment by noname1314** [comment]
@kurokobo 

https://github.com/kurokobo/awx-on-k3s/blob/main/README.md

I am following this guideline to install. DNS set and point to AWX Server.

However, once AWX is installed. I cannot access AWX by FQDN.

I checked the log that traefik proxy does not have IP assigned and compared the workable one. The workable one has IP address and I can access AWX GUI.

Would you please help to advise how can I address this problem?

**Comment by kurokobo** [comment]
Thanks for the update, what I would like to hear is the following.

Versions:

- What is the OS name and version?
- What versions of K3s and AWX Operator do you have?

Environment:

- What is the difference between an "As titled" environment and a "Normal behavior" ("workable") environment?
  - Any difference for the versions for OS/K3s/AWX Operator?
  - Any difference for any files that used to deploy AWX?
  - IP configuration for K3s host? (IPv4/v6, Num of NICs, IP range, ...)

Your situation:

- Have you tried anything to resolve the issue?
- Have you tried re-installing K3s?
- Is it reproducible? In other words, is the result the same no matter how many times you try it on that host?
- Is the pod named like `traefik-*********-*****` working in the `kube-system` namespace?: `kubectl -n kube-system get pod`
- Any logs for the pod?: `kubectl -n kube-system logs traefik-*********-*****`
- What happens if I delete the pod?: `kubectl -n kube-system delete pod traefik-*********-*****`
