### ISSUE TITLE
Could not find or access file on the Ansible Controller

### ISSUE THREAD

**Issue by chaitanya486** [kurokobo/awx-on-k3s#194]
## Environment

- OS: CentOS 8
- Kubernetes/K3s: k3s
- AWX Operator: 1.1.4
We are trying to run the playbook , but it getting failed for below reason.
COuld you please help on that

ERROR:
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [172.17.164.170]: FAILED! => {"changed": false, "dest": "E:\\Initial_Start.bat", "msg": "Could not find or access '/tmp/PROD_donotdelete/Initial_Start.bat' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option", "src": "/tmp/PROD_donotdelete/Initial_Start.bat"}

**Comment by kurokobo** [comment]
@chaitanya486 
Your playbook is invoked inside the EE container, so `/tmp` is the EE container's `/tmp` instead of your controller host.

You have some options to achieve your goal;

- Place your `*.bat` on some remotely accesible storage such as NFS or HTTP and download it in the playbook before use it.
- Create `hostPath` based PV and mount it on the EE using Container Group: https://github.com/kurokobo/awx-on-k3s/tree/main/containergroup

**Comment by kurokobo** [comment]
Lack of information. If you want to get a sufficient answer, first of all provide sufficient information.
I can't give you any advice even if you just say "I have created it" because I know nothing about your actual configuration.

Hints; 

- Ensure you have specified your Container Group as `Instance Groups` of your Job Template
- In my guide, `/data/demo` will be mounted as `/etc/demo` in the EE. You should specify the path for your file as in the EE instead of on your host.

**Comment by chaitanya486** [comment]
Sorry for inconvenience.
We forgot to mention it , we have already updated the job template with the
instance group but as you have mentioned in second point we have to point
/etc/demo path in our playbook.

I will try this and let you know.


Regards,
Chaitanya patil

**Comment by chaitanya486** [comment]
Thanks second point helps , we have given reference to /etc/demo as
mentioned and rerun template , it is executed without any issue.
