### ISSUE TITLE
Getting 

### ISSUE THREAD

**Issue by chaitanya486** [kurokobo/awx-on-k3s#195]
## Environment

- OS: CentOS 8
- Kubernetes/K3s: k3s
- AWX Operator: 1.1.4
We are getting below error while Job execution, some of the jobs are running but most of them are getting failed due to below error.

  "unreachable": true,
  "msg": "Failed to connect to the host via ssh: Unable to negotiate with *************** port 22: no matching host key type found. Their offer: ssh-rsa,ssh-dss",
  "changed": false
}

**Comment by kurokobo** [comment]
> no matching host key type found. Their offer: ssh-rsa,ssh-dss

This error message is the answer. Have you made any investigation on your side?

**Comment by chaitanya486** [comment]
In investigation, Jobs which are failing are not connecting from container.
Also we have check and found in below path from container, entry is present for failling servers.
~/.ssh/known_hosts

tried to connect the server with below command

ssh jboss@******

Unable to negotiate with ****** port 22: no matching host key type found. Their offer: ssh-rsa,ssh-dss

**Comment by kurokobo** [comment]
I mean, you should investigate a bit to know what that error message means.
There is a lot of knowledge about that error on the internet.

**Comment by chaitanya486** [comment]
Hi ,

We are able to connect target server from host. But, we are not able to connect target server from Container which is on the host server.

**Comment by chaitanya486** [comment]
please provide appropriate link so we can implement and try it

**Comment by chaitanya486** [comment]
we have tried this resolution as well but not working

https://github.com/iam-orsu/SSH-troubleshoot/blob/main/Host%20key%20algorithm

**Comment by chaitanya486** [comment]
atlast we came to know the OS version difference where execution is not working has OS version 6.10 and where execution is working having OS version 8.6.

Should be the reason ?

**Comment by kurokobo** [comment]
> atlast we came to know the OS version difference where execution is not working has OS version 6.10 and where execution is working having OS version 8.6.
> Should be the reason ?

Of course yes. Current AWX is based on CentOS Stream 9, and for security reasons, OpenSSL in CentOS Stream 9 doesn't allow some legacy algorithms by default that used in RHEL/CentOS 6 by default.

For security reasons, the legacy algorithms should not be used. Therefore, your first choice should be replacing host key on your RHEL 6 host with newly generated one by ECDSA instead of RSA.
If this is difficult for you, you can use legacy algotithms by some way.

- If you want to use (latest) CentOS 9 based EE:
  - Customize your EE image with `update-crypto-policies` to use `LEGACY` or `DEFAULT:SHA1` (by building custom image) and then make your Job Template to use customized EE
  - In addition to customize EE, pass `-oHostKeyAlgorithms=+ssh-rsa -oPubkeyAcceptedAlgorithms=+ssh-rsa` via `ansible_ssh_common_args` by specifying it in your inventory
- If it's ok for you to use (old) CentOS 8 based EE:
  - Add new EE with tag `quay.io/ansible/awx-ee:21.11.0` (this is the latest 8 based EE) and specify it in your Job Template

**Comment by chaitanya486** [comment]
We are unable to build customize EE image , could you please share steps or give some clarity on how to and which file we have to make changes so that can be used for LEGACY algorithm

**Comment by kurokobo** [comment]
Sorry, I'm tired, you are asking too much in recent your 5 issues.
I am happy to help you develop a better technical understanding, but please don't pass all the costs of solving your issues on to me without doing enough research, trial and error befor asking, providing what you did and what you see, how much you understand and what you do not understand.

Use `quay.io/ansible/awx-ee:21.11.0` instead. This is the simplest solution. Or try to start with following Dockerfile.

```dockerfile
FROM quay.io/ansible/awx-ee:latest
USER root
RUN update-crypto-policies --set LEGACY
USER 1000
```

**Comment by chaitanya486** [comment]
Thanks for the all your help.
As we dont have time bcaz the currently multiple activity is going on and also, we have to do it within 2 days hence if there is solution available that we can apply it directly.

Anyways Thanks for all your help again.
