### ISSUE TITLE
Changing password postgres and AWX

### ISSUE THREAD

**Issue by kasuke5** [kurokobo/awx-on-k3s#27]
First of all, thank you for your amazing job.
Maybe I'm missing something but I recently messed up my awx.
I've changed my `/etc/hostname` and I think it did break some things, anyway I've made some changes inside my AWX so I didn't wanted to lose all my work, that's why I've delete everything except my data which is in the directory `/data/`

Since I wanted to put it in production, I've changed passwords in `base/kustomization.yaml` and I think now postgres cannot access the database
`2022-02-03T15:32:58.888085423+01:00 stderr F 2022-02-03 14:32:58.887 UTC [1486] FATAL:  password authentication failed for user "awx"
2022-02-03T15:32:58.888112407+01:00 stderr F 2022-02-03 14:32:58.887 UTC [1486] DETAIL:  Connection matched pg_hba.conf line 99: "host all all all scram-sha-256"
`
 and I don't know where I can tell it that I've changed password. Is it possible to do this without recreate a new db ? I also put a new password for awx-admin-password but for me, it's only to log in the web interface

**Comment by kurokobo** [comment]
To change the PostgreSQL password while keeping the data, you can usually change it directly with the `psql` command using the shell of the PostgreSQL container. Then, change the password in the `kustomization.yml` and `kubectl apply` again, and AWX will use the new password.

Since we are talking about "How to use PostgreSQL", I think that documenting this much is a bit out of scope 🤔 

In my understanding, just repeating `kubectl apply` without modifying password on PostgreSQL side will not change the password. Also, if you delete everything including secrets on `awx` namespace except for `/data` and rebuild AWX, maybe the Credentials on your AWX are no longer decrypted and can not be used.

**Comment by kasuke5** [comment]
I tried to change the password by going into the postgresql container but I couldn't do any psql command.

And yes you are right, I had to redo my credentials since it was not able to decrypt it anymore :/ 
I'm sorry for my noobiness, I was just struggling with postgres with kubernetes.

**Comment by kurokobo** [comment]
Thanks for updating.
I created this repository for someone who want to use AWX but don't have expertise about k8s, but I believe that Kubernetes and Operator themselves are fundamentally not beginner-friendly. In short, it's complicated.

AWX Operator have ability to take backups and restores, but its operations are not easy to understand unless users are familiar with k8s......

It's not easy to do right away, but I'll consider to add some hints to the guide around your issue. Thanks for the new perspective.
