### ISSUE TITLE
Regularly prune images?

### ISSUE THREAD

**Issue by toutas** [kurokobo/awx-on-k3s#270]
I have been using awx-on-k3s for a while, and I have noticed that awx-ee images keep filling up the disk, requiring me to execute 

`sudo k3s crictl rmi --prune`

It has been a few weeks since it did it previously but today it pruned 50GB of unused images.

Any ideas what we can do? I assume it is an awx operator issue, but in a related issue (https://github.com/ansible/awx-operator/issues/881) they pointed out that k8s has some pruning stuff, so wanted to ask here.

It is not really a serious issue for me, since one possibility is to just setup a regular prune command, but it would be nice to know if you have any alternative fixes.

**Comment by kurokobo** [comment]
@toutas 
Hi, thanks for filling the issue.

As @marek1712 stated above, configuring garbage collection is good way. Refer to the official docs: https://kubernetes.io/docs/concepts/architecture/garbage-collection/#containers-images

There are two params for garbage collection for unused images: 

- `HighThresholdPercent` (default: `85`)
- `LowThresholdPercent` (default: `80`)

Kubelet (bundled in K3s) monitors your `/var/lib/rancher`, so ensure the disk usage exceeds default threshold or not. This is my example.

```bash
$ df -h /var/lib/rancher
Filesystem           Size  Used Avail Use% Mounted on
/dev/mapper/cl-root   40G   26G   14G  65% /
```

In my case, the usage is `65%`, so no garbage collection will be occurred since it is <85. To tune this, we can configure K3s by `--kubelet-args` as @marek1712 shows (only `--kubelet-arg "image-gc-low-threshold=65"` and `--kubelet-arg "image-gc-high-threshold=75"` are required for garbage collection), or directly edit `/etc/systemd/system/k3s.service` as follows:

```bash
# Add following four lines
$ sudo cat /etc/systemd/system/k3s.service
...
ExecStart=/usr/local/bin/k3s \
    server \
        '--write-kubeconfig-mode' \
        '644' \
        '--kubelet-arg' \     👈👈👈
        'image-gc-low-threshold=50' \     👈👈👈
        '--kubelet-arg' \     👈👈👈
        'image-gc-high-threshold=60' \     👈👈👈

# Reload and restart K3s
$ sudo systemctl daemon-reload
$ sudo systemctl restart k3s
```

Wait for 5 minutes since garbage collection for unused images will be invoked every 5 minutes, and then you can monitor the logs for garbage collection. If your unused images are removed, you can see following logs.

```bash
$ sudo journalctl -u k3s --no-pager | grep image_gc_manager
...
... image_gc_manager.go:323] "Disk usage on image filesystem is over the high threshold, trying to free bytes down to the low threshold" usage=65 highThreshold=60 amountToFree=6135992320 lowThreshold=50
... image_gc_manager.go:400] "Removing image to free bytes" imageID="sha256:a9850cb6884c5b98746281986995a35bb9da9b4d98aed878bf9b7df817b00e9a" size=165442214
...
```

If garbage collection is not working properly for some reason, you should be able to see some errors in the logs as well.

@marek1712 
Thanks for your comment!

**Comment by toutas** [comment]
@marek1712 @kurokobo thanks for your answers!

![image](https://github.com/kurokobo/awx-on-k3s/assets/61290992/a454d910-46f9-4009-beda-90f0f8b80bbd)

I have a custom EE and the awx-ee latest execution environments, and both are set up like so in the image, I guess that defaults to always?

I will add these flags to my setup and my currently running host, and see what ends up happening.

**Comment by kurokobo** [comment]
@toutas 
I believe the default policy is ifNotPresent, so I have no idea which images consume disk space on your host. If the garbage collection does not help you, you should investigate with `crictl images` to identify which images consume space.

**Comment by marek1712** [comment]
> @marek1712 Thanks for your comment!

I should thank YOU for the amazing project!!!
Kubernetes/Rancher isn't the tech I work with daily and your guides/replies are great at explaining these things.

Regarding these GC settings: I Googled it after I received an alert from our monitoring system that disk usage exceeded a threshold. Defaults were actually quite close to the values set in the monitoring...
