### ISSUE TITLE
AWX is not accessible post installation

### ISSUE THREAD

**Issue by Saravanaselvaraj** [kurokobo/awx-on-k3s#318]
## Environment

- OS: CentOS-7
- Kubernetes/K3s: v1.28.7+k3s1
- AWX Operator: 2.12.1

## Description

Hi, First of all thank you so much for the excellent work. I have followed the steps in our Google Cloud Platform as it is and made few changes as below according to my requirement.
1. I have not genereted the self signed certificate because I want to get it up running first with http. so skipped the step openssl. 
2. In ./base/awx.yaml , provided my hostname of the GCP server and commented out the line tls_secret since I have not generated the certificate.
**- hostname: XXXX-XX-XXXX-XXXX-1 **
   ** #  tls_secret: awx-secret-tls**
3. Changed the path in pv.yaml for projects and postgres according to my project requirement and created accordingly. 

rest, I followed same steps but I cannot access AWX using hostname provided in awx.yaml. 

When I check this : kubectl -n awx get awx,all,ingress,secrets
```
[svc_usrawxtq01@lpggce-q-ansptchk3s-usea1-1 base]$ kubectl -n awx get awx,all,ingress,secrets
NAME                      AGE
awx.awx.ansible.com/awx   97m

NAME                                                   READY   STATUS    RESTARTS   AGE
pod/awx-operator-controller-manager-7469875f45-8fk5b   2/2     Running   0          3h35m
pod/awx-postgres-13-0                                  1/1     Running   0          96m
pod/awx-task-7bbb4c9885-tcd84                          4/4     Running   0          96m
pod/awx-web-75c9d5ccd7-kknkk                           3/3     Running   0          95m

NAME                                                      TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
service/awx-operator-controller-manager-metrics-service   ClusterIP   XX.XXX.XXX.X   <none>        8443/TCP   3h35m
service/awx-postgres-13                                   ClusterIP   None            <none>        5432/TCP   96m
service/awx-service                                       ClusterIP   X.XX.XXX.X      <none>        80/TCP     96m

NAME                                              READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/awx-operator-controller-manager   1/1     1            1           3h35m
deployment.apps/awx-task                          1/1     1            1           96m
deployment.apps/awx-web                           1/1     1            1           95m

NAME                                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/awx-operator-controller-manager-7469875f45   1         1         1       3h35m
replicaset.apps/awx-task-7bbb4c9885                          1         1         1       96m
replicaset.apps/awx-web-75c9d5ccd7                           1         1         1       95m

NAME                               READY   AGE
statefulset.apps/awx-postgres-13   1/1     96m

NAME                                    CLASS     HOSTS                         ADDRESS         PORTS   AGE
ingress.networking.k8s.io/awx-ingress   traefik   lXXXXXXX-1   XXXXXXX   80      96m

NAME                                  TYPE                DATA   AGE
secret/redhat-operators-pull-secret   Opaque              1      3h35m
secret/awx-admin-password             Opaque              1      98m
secret/awx-postgres-configuration     Opaque              6      98m
secret/awx-secret-tls                 kubernetes.io/tls   2      98m
secret/awx-app-credentials            Opaque              3      96m
secret/awx-secret-key                 Opaque              1      97m
secret/awx-broadcast-websocket        Opaque              1      96m
secret/awx-receptor-ca                kubernetes.io/tls   2      96m
secret/awx-receptor-work-signing      Opaque              2      96m 
```
## Step to Reproduce

1. In GCP Compute Engine, follow all the steps specified and at the end , try to access AWX with the hostname specified in awx.yaml
2. Try to access it from the computer. The URL will not work as expected. It gives below error.
This site can’t be reachedCheck if there is a typo in lXXXXXXXXXXX
DNS_PROBE_FINISHED_NXDOMAIN
4. With IP it gives "404 page not found"
5. I am new to GCP, Actually in AWS, we have public IP and the server can be accessed using public IP. In GCP i am not quite sure what to do. Looks like we need to open some connection in b/n my computer and GCP Server. Please suggest what can be done here.

**Comment by kurokobo** [comment]
Hi, thank you for using my guide!

> generated the certificate.
> - hostname: XXXX-XX-XXXX-XXXX-1 **

Is the actual hostname `XXXX-XX-XXXX-XXXX-1` FQDN? or just the name of the compute engine?

When you've deployed Ingress for HTTP (not HTTPS) as you did, Ingress uses the `host` header of your HTTP request to determine where the traffic to be routed.
So this hostname have to be resolvable by DNS or hosts file.

1. Try accessing `http://<Public IP of your Compute Engine>/` and ensure you can get `404 page not found`. `404` is okay for this case, since the `host` header in your HTTP request is not `XXXX-XX-XXXX-XXXX-1` but `<Public IP of your Compute Engine>`. If you can't get `404`, there might be some connection issues. Please double-check your firewalls on GCP.
2. Try adding `XXXX-XX-XXXX-XXXX-1` to your `hosts` file on your local computer (where your browser is running on), and acccess `http://XXXX-XX-XXXX-XXXX-1/`

**Comment by Saravanaselvaraj** [comment]
Thanks for the quick response. **hostname: XXXX-XX-XXXX-XXXX-1 **  Is just the name of the compute engine. So do I have to modify this with FQDN ?

1. I can find only Internal IP for my GCP server and I cannot see anything under External IP and it is empty. How to mitigate this issue ? PFB 
![Screenshot 2024-03-15 at 17 34 04](https://github.com/kurokobo/awx-on-k3s/assets/57487361/991ae1a1-ce9c-45e2-992b-108a4ddf16fe)
2. I got the AWX working after I added this hostname to my computer's hosts file. Without adding this, we cannot make this work ? Because I am going to share this URL with my colleagues and I don't want to end up adding this entry to all computers. Please help ?

Thanks and Regards

**Comment by kurokobo** [comment]
@Saravanaselvaraj 
Hi, if you got AWX working in step 2 nevertheless you don't have public IP in step 1, I think you don't need any public IP. I guess both your computer and AWX are in the private network. This is safer than making your AWX externally accessible over the internet.
My advice is, if you are unsure about your networking knowledge, you should rely on a colleague who is familiar with it. I have the knowledge about network and internet, but I do not know your organization's network configuration and security policy at all, so I cannot give you the right advice.

> I got the AWX working after I added this hostname to my computer's hosts file. Without adding this, we cannot make this work ? Because I am going to share this URL with my colleagues and I don't want to end up adding this entry to all computers. Please help ?

In general, this is the very reason why we use DNS server. Determine the FQDN for your AWX with the domains available on your internal network and register it with your internal DNS servers. Then specify FQDN for Ingress.

If it's okay for you to access AWX over IP address with the port 30080 instead of hostname with port 80, you can use `service_type: NodePort` and `nodeport_port: 30080` for example, instead of using `service_type: Ingress` and `hostname`. You can specify the port in range of  30000 to 32768.

**Comment by Saravanaselvaraj** [comment]
@kurokobo , Thanks for the information. Soon we are planning to use it with external DB and next in PROD env. I apply all these suggestions during that time. Overall thank you so much for your help and have a nice day ahead.

**Comment by kurokobo** [comment]
@Saravanaselvaraj 
Hi, I'm glad I could help! I'm closing this issue but if you have any further questions in the future feel free to create new issue or create topic on [the forum](https://forum.ansible.com/c/help/6/none) 😃
