### ISSUE TITLE
Looking for help in setting up AWX in multi node environment

### ISSUE THREAD

**Issue by Saravanaselvaraj** [kurokobo/awx-on-k3s#323]
## Environment

- OS: CentOS 7
- Kubernetes/K3s: v1.28.7+k3s1
- AWX Operator: 2.12.1

## Description

Hello, Good day. Please help me with this situation. I am having 3 Servers in total. All are hosted in GCP.  In One of them Postgresql is installed by DBA and they have shared IP and user details. I want to install AWX in other two servers and want to connect to same database . How can I configure this ?
I referred your manual but that is only for single node of deployment with external DB setup. I want to have 3 PODs in first server and 2 Pods in Second Server and the whole system should be connecting to the same DB.

Can you please kindly advice me how can we achieve this using your repo ? I am installing it in QA and hence I don't want to go with Standalone K8S.

Thanks and Regards

**Comment by kurokobo** [comment]
@Saravanaselvaraj 
Hi, have you seen this?
 https://github.com/kurokobo/awx-on-k3s/blob/main/tips/external-db.md

**Comment by kurokobo** [comment]
@Saravanaselvaraj 
Please refer to the Operator's docs: 
https://ansible.readthedocs.io/projects/awx-operator/en/latest/user-guide/advanced-configuration/scaling-the-web-and-task-pods-independently.html

My guide shows only minimal steps and descriptions. If you want to make any customization, I recommend you to read through the official documentation first, rather than relying solely on my guide.

**Comment by Saravanaselvaraj** [comment]
Thank you so much @kurokobo , I will have a look. Have a great day.

Best regards
