### ISSUE TITLE
Unable to send stdout from AWX to pod instance

### ISSUE THREAD

**Issue by vietsoulz** [kurokobo/awx-on-k3s#369]
## Environment
k3s version v1.29.4+k3s1 (94e29e2e)
go version go1.21.9

- OS: Red Hat Enterprise Linux 8.10 (Ootpa) - Linux 4.18.0-553.el8_10.x86_64
- Kubernetes/K3s:
   - Client Version: v1.29.4+k3s1
   - Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
   - Server Version: v1.29.4+k3s1
- AWX Operator: 2.17.0

## Description
I am able to follow your guide and deployed AWX Operator 2.17.0 and AWX 24.4.0.  The PV/PVC mappings worked great and able to  use manual SCM to launch a playbook for Cisco devices.  What I am having trouble is getting the stdout from the ansible's register and save the output to the /var/lib/awx/projects/backkups subfolder.  I keep getting this error:

"path": "/var/lib/awx/projects/backups/ios-xe",
  "msg": "There was an issue creating /var/lib/awx as requested: [Errno 13] Permission denied: b'/var/lib/awx'",
  "invocation": {
    "module_args": {
      "path": "/var/lib/awx/projects/backups/ios-xe",
      "state": "directory",

1. Deploy ...
2. Invoke `kubectl ...`
3. ...
4. ...

## Logs
"path": "/var/lib/awx/projects/backups/ios-xe",
  "msg": "There was an issue creating /var/lib/awx as requested: [Errno 13] Permission denied: b'/var/lib/awx'",
  "invocation": {
    "module_args": {
      "path": "/var/lib/awx/projects/backups/ios-xe",
      "state": "directory",

**Comment by kurokobo** [comment]
@vietsoulz 
Hi, sorry for the late reply, I haven't been feeling well and couldn't find the time to respond.

> What I am having trouble is getting the stdout from the ansible's register and save the output to the /var/lib/awx/projects/backkups subfolder. I keep getting this error:

Your playbook is launched on the ephemeral automation job pod a.k.a. Execution Environment, so `/var/lib/awx/projects` on your playbook is NOT `/data/projects` on your K3s.
If you want to mount a directory on your K3s host to the automation job pod, you have to define Container Group and specify it on your job template.

For your case, try [the **Case 1** of my guide for Container Group](https://github.com/kurokobo/awx-on-k3s/tree/main/containergroup).

I'm closing this since this is explained in another guide, but feel free to create new issue if you have some trouble during following my guide. Thanks!
