### ISSUE TITLE
feature suggestion: ee from private registry

### ISSUE THREAD

**Issue by LeoSpyke96** [kurokobo/awx-on-k3s#48]
Hi, it would be very useful to pull the execution environments images from the AWS Elastic Container Registry, is it possible to implement such feature?

Thank you for everything, this project is awesome! :)

**Comment by kurokobo** [comment]
You can add your own EE through AWX GUI.
<https://docs.ansible.com/automation-controller/latest/html/userguide/execution_environments.html#use-an-ee-in-jobs>

**Comment by LeoSpyke96** [comment]
Thank you for the quick reply.

> You can add your own EE through AWX GUI. https://docs.ansible.com/automation-controller/latest/html/userguide/execution_environments.html#use-an-ee-in-jobs

Yes, maybe I forgot to mention that I'm considering ECR **private** registries.

I already did it what you suggested, and I've configured the proper `Container Registry` credential using `AWS` as username and the output generated by the command `aws ecr get-login-password` as token/password.

The problem here is due to the [12 hours authentication token validity](https://docs.aws.amazon.com/AmazonECR/latest/userguide/registry_auth.html#registry-auth-token) of the ECR service, that forces us to refresh it manually, which is not a sustainable workaround.

**Comment by kurokobo** [comment]
Hmm, I've never know that restriction. Thanks for updating.
I'm not familier with ECR but there is no native function on AWX that updating credentials periodicaly.

So, this is just an idea, not so smart way but should work.
- Create playbook to update credentials using `awx.awx.credential` module; <https://docs.ansible.com/ansible/latest/collections/awx/awx/credential_module.html>
- Run this playbook as Job Template which target AWX itself, with periodic schedule.

Alternatively I recoomend you to ask [the mailing list](https://groups.google.com/g/awx-project) your question.

**Comment by kurokobo** [comment]
Ah, so you have enough expertise about k8s-thing 👍 Thanks for sharing your solution,
Your solution that using `cronJob` and `imagePullSecrets` with customized pod spec is the almost best way I think.

I'm also using `cronJob` to invoke some small script periodicaly. My favorite way is to store the script as `ConfigMap` and attach it to the Job's Pod to simplify the specification for `CronJob`, without making the script hard-coded in specification of `CronJob`.

One thing, I think `kubectl create ... --dry-run -o yaml | kubectl apply -f -` is more stable than simple `kubectl delete; kubectl create`, since the secrets never deleted or dissapeared.

But anyway your solution is good way with less overhead than using AWX's schedule.
