### ISSUE TITLE
Passwords with some special characters cause issues

### ISSUE THREAD

**Issue by seadoox** [kurokobo/awx-on-k3s#54]
## Environment

- OS: Red Hat Enterprise Linux release 8.4 (Ootpa)
- Kubernetes/K3s: v1.22.7+k3s1
- AWX Operator: 0.17.0

## Description
Special characters such as & in the password for awx in the awx-postgres-configuration causes backups using AWXBackup to not work. The backup container would start, create the backup directory, set permissions, but as soon as it would attempt to run the pg_dump it would error out and the container would get terminated. Removing the & from the password fixed it. The awx-operator documentation says that if the password has special characters it should be quoted.

## Step to Reproduce
new install and set the passwords in the kustomization.yaml file to have an & in them then configure and run the backup operator per https://github.com/kurokobo/awx-on-k3s/tree/main/backup

**Comment by kurokobo** [comment]
Thanks, I've never know that and confirmed that this is reproducible on my side.

This behavior came with [this line; the password will be passed without quoting](https://github.com/ansible/awx-operator/blob/5375fec77d02fec5d0763a5910a643bec6eeb32f/roles/backup/tasks/postgres.yml#L102).

> The awx-operator documentation says that if the password has special characters it should be quoted.

True. But I believe this was probably added without testing. If the password was quoted, [it will be quoted twice in `credentials.py`](https://github.com/ansible/awx-operator/blob/5375fec77d02fec5d0763a5910a643bec6eeb32f/roles/installer/templates/credentials.py.j2#L7), so I beleave the AWX can't connect DB in the first place due to wrong password which includes quotes.

Therefore, the password should not be quoted by user, but shoud be quoted by Operator. This is an issue of Operator, so new issue on Operator's repository should be created.

Of course I can, but if you like, you can create an issue of this matter in Operator's repository.

**Comment by seadoox** [comment]
Go ahead if you don't mind. Thank you for all of your effort on this
project! It is super helpful.

**Comment by kurokobo** [comment]
Thanks for updating, as a workaround, I've add note for usable letteres in password:

> Note that some special charactors like `&`, `$`, etc. in `password` under `awx-postgres-configuration` might cause the deployment issue. Not tested all charactors, but `!` is safe to use at least.
> https://github.com/kurokobo/awx-on-k3s#prepare-required-files

**Comment by KlutzyBubbles** [comment]
> Thanks for updating, as a workaround, I've add note for usable letteres in password:
> 
> > Note that some special charactors like `&`, `$`, etc. in `password` under `awx-postgres-configuration` might cause the deployment issue. Not tested all charactors, but `!` is safe to use at least.
> > https://github.com/kurokobo/awx-on-k3s#prepare-required-files

From my pain the past few days it seems `.` cant be used either.

**Comment by kurokobo** [comment]
@seadoox @KlutzyBubbles 
Just for your information, I made a PR ansible/awx-operator#838 for this issue for the upstream, and the PR had released with `0.19.0`.
I've confirmed that the issue solved with Operator `0.19.0` on my side.
