### ISSUE TITLE
Adding tips to set proxy settings

### ISSUE THREAD

**Issue by jheinitz** [kurokobo/awx-on-k3s#79]
Hello,

I wanted to add an extra tips page to add custom proxy setting for the awx-web, awx-task and awx-ee containers, but I don not have permission to push my branch. 
Would you mind adding me to the list of contributors? I'm in the early stage of conributing to projects in GitHub, but I'm willing to learn. 

Thanks and best regards
Jens

**Comment by kurokobo** [comment]
@jheinitz 
Hi, thanks for beeing interested in contributing to this project 😃 

> Would you mind adding me to the list of contributors?

Since this is a good opportunity for you, let me briefly explain how to become a contributer.

In GitHub, the most standard way to become a contributor is to send a _Pull Request_ (PR), get reviewed, and get merged. To achieve this, do following:

1. Fork this repository via Web UI. This will create a copy of this project as https://github.com/jheinitz/awx-on-k3s
2. Clone forked project to your workstation.
3. Create a branch on your workstation.
4. Make changes on your workstation.
5. Stage and commit changes on your workstation.
6. Push the commit to GitHub.
7. Submit the commit as new pull request to my repository.
8. Wait for me to review the PR. Sometimes I will request additional modification to improve things.
9. Once your PR will be merged, you are now the one of the contributer. You will be listed on the _Contributers_ list automatically.

There is a good tutorial repos for beginners: https://github.com/firstcontributions/first-contributions

I want you to try it. Thanks 😃

**Comment by jheinitz** [comment]
Hi! 
I think I know what my fault is. I cloned your repo to my workstation (Linux) and performed a `git branch jens` followed by a `git checkout jens` and tried to push this branch to your repo, but now I know that I need to fork your repo first. 

I will try your suggestion later.

Thanks and best regards

Jens

**Comment by jheinitz** [comment]
PR created. Looking forward to your feedback. Jens
