### ISSUE TITLE
Cannot copy file from awx to remote host

### ISSUE THREAD

**Issue by hoanbc** [kurokobo/awx-on-k3s#81]
## Environment

- OS: RHEL
- Kubernetes/K3s: k3s version v1.23.6+k3s1 (418c3fa8)
- AWX Operator: 0.21.0

## Description
I want copy file from awx to remote host, but i don't understand how to it work. It show me an error as below.
Could not find or access 'copyfile.txt'\nSearched in:\n\t/runner/project/files/copyfile.txt\n\t/runner/project/copyfile.txt\n\t/runner/project/files/copyfile.txt\n\t/runner/project/copyfile.txt on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option",

I don't know /runner/project is where. I did try go to awx-ee and create copyfile.txt in there but it not working.

ERROR
{
  "msg": "Could not find or access 'copyfile.txt'\nSearched in:\n\t/runner/project/files/copyfile.txt\n\t/runner/project/copyfile.txt\n\t/runner/project/files/copyfile.txt\n\t/runner/project/copyfile.txt on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option",
  "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/ansible/plugins/action/copy.py\", line 466, in run\n    source = self._find_needle('files', source)\n  File \"/usr/local/lib/python3.8/site-packages/ansible/plugins/action/__init__.py\", line 1364, in _find_needle\n    return self._loader.path_dwim_relative_stack(path_stack, dirname, needle)\n  File \"/usr/local/lib/python3.8/site-packages/ansible/parsing/dataloader.py\", line 341, in path_dwim_relative_stack\n    raise AnsibleFileNotFound(file_name=source, paths=[to_native(p) for p in search])\nansible.errors.AnsibleFileNotFound: Could not find or access 'copyfile.txt'\nSearched in:\n\t/runner/project/files/copyfile.txt\n\t/runner/project/copyfile.txt\n\t/runner/project/files/copyfile.txt\n\t/runner/project/copyfile.txt on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option\n",
  "invocation": {
    "src": "copyfile.txt",
    "dest": "/opt/",
    "module_args": {
      "src": "copyfile.txt",
      "dest": "/opt/"
    }
  },
  "_ansible_no_log": false,
  "changed": false
}

**Comment by kurokobo** [comment]
@hoanbc 
Thanks for filling the issue.

### The short answer

Place your `copyfile.txt` on the project root directory, or under the `files` directory that placed on the project root.
I mean, if you are using [hoanbc/test](https://github.com/hoanbc/test) as your project, `copyfile.txt` should be either:

```text
.
|-- hello_world.yml
|-- copyfile.txt     👈 here,
`-- files
    `-- copyfile.txt     👈 or here
```

### The long answer

Your playbook will be executed inside the volatile pod that called _Execution Environment_ (EE). Yes, the `awx-ee` is the one of the EE, but this is not for your playbook, but for internal management job. The EE for your playbook will be created as the pod named `automatuon-job-*` at the run time, and will be deleted once your playbook will be finished.

`/runner/project` is the directory inside the volatile EE. The all files under your project will be copied to this directory at the run time. So, you should place your `copyfile.txt` in your project directory.

If you want to use the file that placed on the K3s host, since that file can't be touched from inside the volatile EE, you should create additional PV/PVC and specify it by defining customized specification for the Container Group. Refer my guide for detail: <https://github.com/kurokobo/awx-on-k3s/tree/main/containergroup>

**Comment by hoanbc** [comment]
Hi @kurokobo 

I did try put my file need copy to project directory but it not work. Please review my playbook and confirm this is true.
[root@srv-awx _9__project_test]# pwd
/data/projects/_9__project_test
[root@srv-awx _9__project_test]# ls -la
-rw-r--r-- 1 root   root     9 May 29 01:46 copyfile.txt
drwxr-xr-x 2 root   root    26 May 29 11:11 files
-rw-r--r-- 1 devops root   219 May 29 11:14 hello_world.yml
[root@srv-awx _9__project_test]# ls -la files/
-rw-r--r-- 1 root   root  9 May 29 11:11 copyfile.txt

My playbook.yml
- name: Copy file
  hosts: all
  tasks:
    - name: Copy file
      ansible.builtin.copy:
        src: copyfile.txt
        dest: /opt/

**Comment by kurokobo** [comment]
@hoanbc 
Hi, if your project type is SCM, any manual modification under `/data/projects/_9__project_test` will not be copied to the EE.
Place your `copyfile.txt` in the SCM and update your project to make your `copyfile.txt` visible in the EE.

**Comment by hoanbc** [comment]
Hi.

Nice, this working. Thank for tutorial me.
