### ISSUE TITLE
Changing default ports

### ISSUE THREAD

**Issue by everydaylearner** [kurokobo/awx-on-k3s#85]
Hello,

Thank you for this, really appreciate it!. Where can i change the port number? say i want to run on port 8443 rather than default port 80?

Thank you!

**Comment by kurokobo** [comment]
@everydaylearner 
Hi, thanks for using my guide :)

> Where can i change the port number? say i want to run on port 8443 rather than default port 80?

You mean, your AWX is already accesible via _HTTP_ over 80 and _HTTPS_ over 443, but you want to use _HTTPS over 8443_ instead, right?

**Comment by everydaylearner** [comment]
yes correct, i want to run over 8443

Thank you!

**Comment by kurokobo** [comment]
Okay, so you should to know _the port 8443 on your K3s host is already used by Traefik by default_, to route HTTPS traffic internally.

```bash
$ kubectl -n kube-system get deployment traefik -o=jsonpath='{.spec.template.spec.containers[0].ports}' | jq
...
  {
    "containerPort": 8443,
    "hostPort": 8443,     👈👈👈
    "name": "websecure",
    "protocol": "TCP"
  }
...
```

Traefik has the feature called [EntryPoints](https://doc.traefik.io/traefik/routing/entrypoints/) to expose custom ports, but 8443 can't be used due to this confliction.

So, there are two way to achieve your requirements.

1. Expose 8443 that Traefik uses internally to the host network.
2. Change internal port for Traefik from 8443, and then create custom EntryPoints.

The method 1 is a bit dirty and un-secure since unintended ports such as 8000, 9000, 9100 will also be exposed, but simple.

```bash
# Create custom configuration file for Traefik
sudo tee /var/lib/rancher/k3s/server/manifests/traefik-config.yaml <<EOF
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    hostNetwork: true
EOF

# Then wait until your traefik by the following command is 1/1 READY.
kubectl -n kube-system get deployment traefik
```

Now your 8443 is accessible via HTTPS

Method 2 is a bit complicated and there might be some side effects.

```bash
# Create custom configuration file for Traefik
sudo tee /var/lib/rancher/k3s/server/manifests/traefik-config.yaml <<EOF
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      websecure:
        port: 8442
        expose: true
        exposedPort: 443
        protocol: TCP
        tls:
          enabled: true
      mywebsecure:
        port: 8443
        expose: true
        exposedPort: 8443
        protocol: TCP
        tls:
          enabled: true
    entryPoints:
      mywebsecure:
        address: ":8443"
EOF

# Then wait until your traefik by the following command is 1/1 READY.
kubectl -n kube-system get deployment traefik
```

**Comment by everydaylearner** [comment]
thank you very much! Appreciate it! It helps to understand better. I think i need to read more on traefik.
