### ISSUE TITLE
collections are not getting detected

### ISSUE THREAD

**Issue by rajspeed1** [kurokobo/awx-on-k3s#92]
Hi,

I've recently upgraded my awx version to k3s. 
Playbook is getting failed at the below task.  Previous tasks were running fine.  
Same playbook is running fine, with the older version of AWX (but on docker)

Can you pls. suggest if this is common on this version ..?? 

- set_fact:
resource_num: "{{ resource_details.response | list | json_query('[?type == `Microsoft.DBforPostgreSQL/servers`].name' )  }}"

Error:
**template error while templating string: unable to locate collection community.general**

On the job logs:
ansible collection location = /runner/requirements_collections:/home/runner/.ansible/collections:/usr/share/ansible/collections

I can see all the collections are existing on /home/runner/.ansible/collections

ansible-galaxy  collection list
# /usr/share/ansible/collections/ansible_collections
Collection              Version
----------------------- -------
amazon.aws              3.3.0
ansible.posix           1.4.0
ansible.windows         1.10.0
awx.awx                 21.1.0
azure.azcollection      1.13.0
community.vmware        2.6.0
google.cloud            1.0.2
kubernetes.core         2.3.2
openstack.cloud         1.8.0
ovirt.ovirt             2.1.0
redhatinsights.insights 1.0.7
theforeman.foreman      3.4.0

# /home/runner/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 5.1.1

**Comment by kurokobo** [comment]
@rajspeed1 
Hi, thanks for filling the issue.

I need more detail. Please do not suppress the message on your side and please paste the complete error. It's hard for me to understand your situation from your comment.

```text
- set_fact:
resource_num: "{{ resource_details.response | list | json_query('[?type == `Microsoft.DBforPostgreSQL/servers`].name' )  }}"
```

Why did you paste this line? Is this line related to that error? 

> I can see all the collections are existing on /home/runner/.ansible/collections
> ansible-galaxy  collection list

How did you invoke these commands?

And you should use markdown syntax to make your comment easy to read. For example `- ` and `# ` in your comment have special meaning in markdown, so your `- ` is displayed as list, `# ` is displayed as headline.

If you wan't to paste something, please wrap your text block with triple-backquotes like:

````
```
Some text you want to paste
```
````

**Comment by kurokobo** [comment]
I seem to have told you the same thing a month ago: https://github.com/kurokobo/awx-on-k3s/issues/78#issuecomment-1132736461

Please keep your questions easy to read and understand for the respondent. Thanks.

**Comment by rajspeed1** [comment]
Hi @kurokobo  - Sorry for the wrong syntaxes..Yes Set Fact is the line, where its failing with

**Comment by kurokobo** [comment]
### The short answer

The collection `community.general` is not installed on the default EE `awx-ee:latest`.

You should place `collections/requirements.yml` or build and use custom EE.

### The long answer

When you invoke your playbook using AWX, your playbook will be invoked inside the container that called Execution Environment (EE). All collections used in the playbook have to be installed in the container image for the EE.

So, I think that something what you are missing is EE, and your issue is also related to the EE you are using. You should learn about EE.

- [What's new in Ansible Automation Platform 2: automation execution environments](https://www.ansible.com/blog/whats-new-in-ansible-automation-platform-2-automation-execution-environments)
- [14. Execution Environments — Automation Controller User Guide v4\.2\.0](https://docs.ansible.com/automation-controller/latest/html/userguide/execution_environments.html)

If the Source Control Type of your project is SCM, [you can fix by creating `collections/requirements.yml` on your project root and listing required collections in it](https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#install-multiple-collections-with-a-requirements-file). If your project is Manual type, the preffered way is to [build your own custom EE image and  push it to your container registry](https://github.com/kurokobo/awx-on-k3s/tree/main/builder), and use it from AWX.

The list of collections you provided is, I guess, not the collections installed _in your EE_ but the collections installed _in your K3s host_. The EE runs as a completely separate environment from your K3s host, so collections installed on your host are never used. Again, you should learn about EE.

This is just a side note. however, when I try to reproduce your issue in my environment, there is only less information so it's hard for me to prepare environment to reproduce your issue. I don't know your OS, the version of K3s, the version of AWX Operator, the version of AWX, which EE is used, where your EE came from, which Ansible version is installed in EE, example minimal playbook to reproduce issue, what AWX and Ansible version were used before. And I don't know what you tried, what you searched.

I wrote that please keep your questions easy to read and understand, which means that information that only you know is important to solve your issue, and there is no way for me to know that unless you write it down.

Providing sufficient information is absolutely necessary for a satisfactory answer. Please do not omit anything that is obvious to you and provide as much information as possible.
