### ISSUE TITLE
no matches for kind "Kustomization" in version "kustomize.config.k8s.io/v1beta1"

### ISSUE THREAD

**Issue by the02** [kurokobo/awx-on-k3s#94]
## Environment
k3s version v1.23.6+k3s1 (418c3fa8)
go version go1.17.5

- OS: Debian 11
- AWX Operator: 0.22.0

## Description
On fresh deployment, when following the instructions it shows me

error: unable to recognize "base/kustomization.yaml": no matches for kind "Kustomization" in version "kustomize.config.k8s.io/v1beta1"
when running kubectl apply -k base

Final result is, that all pods are up and running but I get a "Bad gateway" when accessing in the browser.
checking the logs with kubectl -n awx logs statefulset/awx-postgres it says then
FATAL:  password authentication failed for user "awx"

## Step to Reproduce
follow the steps until kubectl apply -k base

**Comment by kurokobo** [comment]
@the02 
Thanks for filling this.
Ensure your `kubectl` binary is the one that came with K3s? If your `kubectl` is K3s' one, it should be symbolic link to `k3s`.

```bash
$ which kubectl
/usr/local/bin/kubectl

$ ls -l $(which kubectl)
lrwxrwxrwx. 1 root root 3 Jun 10 20:38 /usr/local/bin/kubectl -> k3s
```

I guess your `kubectl` is not `kubectl` that came with K3s. K3s installer skips installation of `kubectl` if `kubectl` already exists.

So, the solution is the one of these:

- Remove your `kubectl` binary and run K3s installer script again.
- Use `k3s kubectl` command instead of just `kubectl` e.g. `k3s kubectl apply -k base`

**Comment by the02** [comment]
confirmed
```
~$ ls -la $(which kubectl )
lrwxrwxrwx 1 root root 3 Jun 14 08:41 /usr/local/bin/kubectl -> k3s
```

After completely removing anything related to awx-operator and awx-on-k3s (all pods, pv, pvc, data in the mapped folders) and starting again it worked. dont know what caused the issue initially

**Comment by kurokobo** [comment]
@the02 
Hi, thanks for updating. I have reconsidered that the error comes from the API side, so it was not a client-side problem.
It may be that K3s was not fully booted, or temporarily that the api server included in K3s may not have been working properly.
Anyway thanks for reporting and closing 😃
